### ISSUE TITLE
Fix Issue: Permissions not working correctly.

### ISSUE THREAD

**Issue by actuallytinh** [AndreasHGK/EasyKits#45]
**Details**
When using the permission, `easykits.free.<kitname>` , it doesn't allow me to claim the kit for free. I tried multiple different ways to fix it but I still couldn't claim it. I always end up with having the error message:
![image](https://user-images.githubusercontent.com/62217004/96648185-fec03500-12fc-11eb-959e-e2e1d95222ed.png)
I tried tackling this issue different ways to see if it was just user issue but I couldn't get it to work. I even checked in the file
**Kit.php** to see if there was a way to fix it but everything seemed fine.

**kit.yml**
```yml
leaxin:
  items: []
  armor:
  - id: 306
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWUQAMKnMUV4YW1wbGUgQm9vdHMAAA==
    format: nbt
  - id: 307
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWUTAMKnMUV4YW1wbGUgTGVnZ2luZ3MAAA==
    format: nbt
  - id: 308
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWUVAMKnMUV4YW1wbGUgQ2hlc3RwbGF0ZQAA
    format: nbt
  - id: 309
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWURAMKnMUV4YW1wbGUgSGVsbWV0AAA=
    format: nbt
  price: 5000.000000
  cooldown: 5
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: false
  permission: easykits.kit.leaxin
Sword:
  items:
  - id: 276
  armor:
  - id: 306
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWUQAMKnMUV4YW1wbGUgQm9vdHMAAA==
    format: nbt
  - id: 307
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWUTAMKnMUV4YW1wbGUgTGVnZ2luZ3MAAA==
    format: nbt
  - id: 308
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWUVAMKnMUV4YW1wbGUgQ2hlc3RwbGF0ZQAA
    format: nbt
  - id: 309
    nbt_b64: CgAACgcAZGlzcGxheQgEAE5hbWURAMKnMUV4YW1wbGUgSGVsbWV0AAA=
    format: nbt
  price: 5000.000000
  cooldown: 20
  flags:
    locked: false
    doOverride: false
    doOverrideArmor: false
    alwaysClaim: false
    emptyOnClaim: false
    chestKit: false
  permission: sword
...                                                                                                                                                                                                               
```
**Kit Selection Menu**
![image](https://user-images.githubusercontent.com/62217004/96649601-73946e80-12ff-11eb-8fcb-93419527e243.png)

**What I did for the first kit:**
I first created the kit with the permission `easykits.free.leaxin` in the field. After that, I added the exact permission to my player. When I tried claiming the kit with `/kit leaxin`, it sent me the error message which is above.
(I know I used the permission field the wrong way and it was supposed to used only for `easykits.kit.<name>`, but I wanted to try anyways.)

**What I did for the second kit:**
For the second kit, its pretty much the same things inside, but this time for the permission, I just put `sword`. I then added the permission `easykits.free.sword` to my player, and tried claiming it. It still showed that I had insufficient funds.

**What I did for the third kit (not shown in kits.yml because I added this one later):**
It was pretty much the same kit, except I left the field blank which was said to default it to the kits name, which was `okay1`. And then added the permission `easykits.free.okay1`. Tried claiming it, and failed again.


I don't know if any of the methods I used are right or wrong, I just know what I have tried hasn't worked. It could just be me not setting up the kits right. Any way to fix this?
